FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_APP_MODE=production
ARG VITE_PUBLIC_APP_BASE_DOMAIN=homelabshare.gr
ARG VITE_CENTRAL_PORTAL_DOMAIN=gas.homelabshare.gr
ARG VITE_DEFAULT_TENANT_SLUG=bp-kallis
ARG VITE_ENABLE_MONTHLY_PDF_ARCHIVE=false

ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID
ENV VITE_APP_MODE=$VITE_APP_MODE
ENV VITE_PUBLIC_APP_BASE_DOMAIN=$VITE_PUBLIC_APP_BASE_DOMAIN
ENV VITE_CENTRAL_PORTAL_DOMAIN=$VITE_CENTRAL_PORTAL_DOMAIN
ENV VITE_DEFAULT_TENANT_SLUG=$VITE_DEFAULT_TENANT_SLUG
ENV VITE_ENABLE_MONTHLY_PDF_ARCHIVE=$VITE_ENABLE_MONTHLY_PDF_ARCHIVE

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

RUN mkdir -p /tmp/nginx \
  && chown nginx:nginx /tmp/nginx \
  && sed -i 's|^[[:space:]]*pid[[:space:]].*;|pid /tmp/nginx/nginx.pid;|' /etc/nginx/nginx.conf \
  && grep -qx 'pid /tmp/nginx/nginx.pid;' /etc/nginx/nginx.conf

USER nginx

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1:8080/ >/dev/null || exit 1
