import { Info, Pencil, RotateCcw, X } from 'lucide-react';
import { SHIFT_TYPES } from '../../utils/analytics';

function getTypeClass(type) {
  switch (type) {
    case SHIFT_TYPES.REST:
      return 'border-slate-500/60 bg-slate-500/50 text-white';
    case SHIFT_TYPES.LEAVE:
      return 'border-orange-500/60 bg-orange-500/50 text-white';
    case SHIFT_TYPES.SICK:
      return 'border-red-500/60 bg-red-500/50 text-white';
    case SHIFT_TYPES.WORK:
    default:
      return '';
  }
}

export function isAutoGeneratedNote(note) {
  const value = `${note || ''}`.trim().toLowerCase();
  return (
    value.startsWith('auto-generated') ||
    value.startsWith('auto generated') ||
    value.startsWith('auto-generated weekly coverage') ||
    value.startsWith('auto-generated 3-employee coverage') ||
    value.startsWith('auto-generated sunday fairness') ||
    value.startsWith('auto-generated intermediate')
  );
}

function getCompactNonWorkLabel(type) {
  switch (type) {
    case SHIFT_TYPES.LEAVE:
      return 'ΑΔ';
    case SHIFT_TYPES.SICK:
      return 'ΑΣ';
    case SHIFT_TYPES.REST:
    default:
      return 'ΑΝ';
  }
}

const DENSITY_CLASSES = {
  compact: {
    card: 'px-2 py-1 text-[11px]',
    name: 'text-[12px]',
    time: 'text-[11px]',
  },
  comfortable: {
    card: 'px-2.5 py-1.5 text-[12px]',
    name: 'text-[13px]',
    time: 'text-[12px]',
  },
  roomy: {
    card: 'px-3 py-2 text-[13px]',
    name: 'text-sm',
    time: 'text-[13px]',
  },
};

export default function AssignedShiftItem({
  shift,
  employee,
  hasConflict,
  onDelete,
  onEdit,
  onToggleManualOverride,
  canManage = true,
  density = 'comfortable',
}) {
  const type = shift.type || SHIFT_TYPES.WORK;
  const isWork = type === SHIFT_TYPES.WORK;
  const typeClass = getTypeClass(type);
  const canEdit = canManage && typeof onEdit === 'function';
  const canDelete = canManage && typeof onDelete === 'function';
  const canToggleManual = canManage && typeof onToggleManualOverride === 'function';
  const hasActions = canEdit || canDelete;
  const manualNote = shift.notes && !isAutoGeneratedNote(shift.notes) ? shift.notes : '';
  const displayTime = isWork ? `${shift.startTime} - ${shift.endTime}` : getCompactNonWorkLabel(type);
  const employeeName = employee?.fullName || shift.employeeName || 'Άγνωστος';
  const densityClasses = DENSITY_CLASSES[density] || DENSITY_CLASSES.comfortable;

  return (
    <article
      title={manualNote || undefined}
      data-testid="assigned-shift"
      data-date={shift.date || ''}
      data-employee-id={shift.employeeId || ''}
      data-employee-name={employeeName}
      data-shift-type={shift.shiftType || type}
      data-start-time={shift.startTime || ''}
      data-end-time={shift.endTime || ''}
      className={`relative rounded-md border leading-snug shadow-sm backdrop-blur-sm ${densityClasses.card} ${
        typeClass ||
        (hasConflict
          ? 'border-red-400 bg-red-100/80 dark:border-red-300/60 dark:bg-red-500/20'
          : 'border-white/35 bg-white/55 dark:border-cyan-300/30 dark:bg-slate-900/45')
      }`}
    >
      {hasActions ? (
        <div className="absolute right-1 top-1 flex items-center gap-0.5">
          {canEdit ? (
            <button
              type="button"
              onClick={() => onEdit?.(shift)}
              className="rounded p-0.5 text-slate-500 hover:bg-sky-100 hover:text-sky-700 dark:text-slate-300 dark:hover:bg-sky-500/30 dark:hover:text-sky-200"
              title="Επεξεργασία"
              aria-label="Επεξεργασία βάρδιας"
            >
              <Pencil size={13} />
            </button>
          ) : null}
          {canDelete ? (
            <button
              type="button"
              onClick={() => onDelete?.(shift.id)}
              className="rounded p-0.5 text-slate-500 hover:bg-red-100 hover:text-red-600 dark:text-slate-300 dark:hover:bg-red-500/30 dark:hover:text-red-200"
              title="Αφαίρεση"
              aria-label="Αφαίρεση βάρδιας"
            >
              <X size={13} />
            </button>
          ) : null}
        </div>
      ) : null}

      <div className="min-w-0 pr-10">
        <p className={`break-words font-bold leading-snug text-slate-900 dark:text-white ${densityClasses.name}`}>
          {employeeName}
        </p>
        <p className={`mt-0.5 whitespace-nowrap font-semibold leading-snug text-slate-700 dark:text-slate-100 ${densityClasses.time}`}>
          {displayTime}
        </p>
      </div>

      <div className="mt-1 flex items-center gap-1">
        {shift.isManualOverride ? (
          <span className="inline-flex rounded-full border border-fuchsia-300/70 bg-fuchsia-100/80 px-1 py-0.5 text-[9px] font-semibold text-fuchsia-900 dark:border-fuchsia-300/40 dark:bg-fuchsia-500/20 dark:text-fuchsia-100">
            M
          </span>
        ) : null}
        {canToggleManual ? (
          <button
            type="button"
            onClick={() => onToggleManualOverride?.(shift.id, !shift.isManualOverride)}
            className="inline-flex items-center rounded border border-slate-300/70 p-0.5 text-slate-600 hover:bg-white/70 dark:border-cyan-300/35 dark:text-slate-200 dark:hover:bg-slate-800/60"
            title={shift.isManualOverride ? 'Καθαρισμός manual override' : 'Mark manual'}
            aria-label={shift.isManualOverride ? 'Καθαρισμός manual override' : 'Mark manual'}
          >
            <RotateCcw size={10} />
          </button>
        ) : null}
        {manualNote ? (
          <span
            className="inline-flex items-center text-slate-500 dark:text-slate-300"
            title={`Σημείωση: ${manualNote}`}
            aria-label="Υπάρχει σημείωση"
          >
            <Info size={10} />
          </span>
        ) : null}
      </div>

      {shift.isHoliday || shift.isSpecialDay ? (
        <p className="mt-0.5 inline-flex rounded-full border border-amber-300/70 bg-amber-100/80 px-1 py-0.5 text-[9px] font-semibold text-amber-900 dark:border-amber-300/40 dark:bg-amber-500/20 dark:text-amber-100">
          {shift.specialDayLabel?.trim()
            ? `Ειδικό: ${shift.specialDayLabel}`
            : shift.isHoliday
              ? 'Αργία'
              : 'Ειδικό Ωράριο'}
        </p>
      ) : null}

      {hasConflict && isWork ? (
        <p className="mt-0.5 font-medium text-red-700 dark:text-red-300">Επικάλυψη</p>
      ) : null}
    </article>
  );
}
