import {
  createShift,
  createShiftTemplate,
  fetchShiftsByDates,
  fetchShiftsOnce,
  hasConsecutiveSundayAssignment,
  removeShift,
  removeShiftTemplate,
  removeShiftsByDates,
  removeShiftsByEmployee,
  replaceShiftsBatch,
  restoreShift,
  subscribeShifts,
  subscribeShiftTemplates,
  updateShift,
  updateShiftTemplate,
} from '../../firebase/shiftService';

export const firebaseShiftsRepository = {
  subscribeShifts,
  subscribeShiftTemplates,
  listShifts: fetchShiftsOnce,
  listShiftsByDates: fetchShiftsByDates,
  createShift,
  updateShift,
  deleteShift: removeShift,
  restoreShift,
  deleteShiftsByEmployee: removeShiftsByEmployee,
  deleteShiftsByDates: removeShiftsByDates,
  createShiftTemplate,
  updateShiftTemplate,
  deleteShiftTemplate: removeShiftTemplate,
  replaceShiftsBatch,
  hasConsecutiveSundayAssignment,
};
